### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [MeinKraft/Crimson-Junk-Bags#1]
`Minecraft v1.16.4`
`Forge v35.1.15`
`Junk Bags v1.0.0`

**Describe the bug**
- The server crashed immediately after right-clicking a food bag.
- [Crash Report](https://gist.github.com/WenXin20/63cb35067f60f8be291df12fab661c4c)

**To Reproduce**
1. Load on server
2. Right-click food bag
3. Crash

**Expected behavior**
- No crashes

**Comment by MeinKraft** [comment]
Version 1.0.1
Silly client side methods - all fixed - you can now shift click Junk Bags

Commands are NOT working serverside - as im new to modding Im not fully aware of why or how configs are handled.  So you'll have to set the loot client side and upload the configs to the server <- this is not guaranteed, I need more knowledge

**Comment by WenXin20** [comment]
Alright, no worries. Thanks!
